# Generated by Django 4.1 on 2022-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('lyrics', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
            ],
        ),
    ]
