# Generated by Django 4.1 on 2022-11-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.artist'),
        ),
    ]
