# Generated by Django 4.1 on 2022-11-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_media_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='views',
        ),
    ]
